spring:
  datasource:
    url: jdbc:mysql://192.168.0.103:3306/legenddisk?serverTimezone=UTC
    username: root
    password: Lyb19961016!
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9080
  servlet:
    context-path: /legenddisk
logging:
  level:
    com.service.legenddisk.mapper: debug