spring:
  datasource:
    url: jdbc:mysql://localhost:3306/legenddisk?serverTimezone=UTC
    username: root
#    password: Lyb19961016!
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#    session保存的数据库类型
  session:
    store-type: redis
#    配置redis
  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
server:
  port: 9080
  servlet:
    context-path: /legenddisk
logging:
  level:
    com.service.legenddisk.mapper: debug
debug: true

